QT   += core gui widgets uitools
CONFIG += qt
CONFIG += c++11
CONFIG += lrelease
SOURCES += main.cpp
SOURCES += Form.cpp
HEADERS += Form.h
RESOURCES += form.qrc
# TRANSLATIONS += mlc_C.ts
# TRANSLATIONS += mlc_de.ts
